// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjltpyadxrahtynlrhgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbHRweWFkeHJhaHR5bmxyaGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDMyMDUsImV4cCI6MjA2NTM3OTIwNX0.x3YP-v2e3rTA2dWVyKcsRhQkXWvi0hLZYxJmZmtvMRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});